# Levenshtein from Scratch with Julia

References:
1. https://en.wikipedia.org/wiki/Levenshtein_distance
2. https://rawgit.com/ztane/python-Levenshtein/master/docs/Levenshtein.html
3. https://www.datacamp.com/community/tutorials/fuzzy-string-python

### Levenshtein Distance and Ratio Step by Step

Let's start off by writing the Levenshtein distance and ratio calculations step by step

We will compare the two strings below:

In [30]:
source = "Levenshtein"
target = "Lenvinsten"

"Lenvinsten"

In [6]:
# get the dimensions to set up the Distance Matrix
r = length(source)+1
c = length(target)+1
println((r,c))

(12, 11)


In [7]:
# Initialize the matrix with zeros
D = Array{Float64, 2}(undef, length(source)+1, length(target)+1)
fill!(D, 0)

12×11 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [8]:
# let the first row and col be populated by the indices of source and target
for row = 2:r
    for col = 2:c
        D[row, 1] = row-1
        D[1, col] = col-1
    end
end

In [9]:
# let's check out our matrix
D

12×11 Matrix{Float64}:
  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
  4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
  5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
  6.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
  8.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
  9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
 10.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
 11.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0

In [10]:
# iterate over the matrix to compute cost of deletions, insertions, substitions
for row = 2:r
    for col = 2:c
        if source[row-1] == target[col-1]
            substitutionCost = 0
        else
            substitutionCost = 1
        end
        D[row, col] = minimum((D[row-1, col] + 1, D[row, col-1] + 1, D[row-1, col-1] + substitutionCost))
    end
end

In [11]:
D

12×11 Matrix{Float64}:
  0.0   1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
  1.0   0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0   9.0
  2.0   1.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0   8.0
  3.0   2.0  1.0  1.0  1.0  2.0  3.0  4.0  5.0  6.0   7.0
  4.0   3.0  2.0  2.0  2.0  2.0  3.0  4.0  5.0  5.0   6.0
  5.0   4.0  3.0  2.0  3.0  3.0  2.0  3.0  4.0  5.0   5.0
  6.0   5.0  4.0  3.0  3.0  4.0  3.0  2.0  3.0  4.0   5.0
  7.0   6.0  5.0  4.0  4.0  4.0  4.0  3.0  3.0  4.0   5.0
  8.0   7.0  6.0  5.0  5.0  5.0  5.0  4.0  3.0  4.0   5.0
  9.0   8.0  7.0  6.0  6.0  6.0  6.0  5.0  4.0  3.0   4.0
 10.0   9.0  8.0  7.0  7.0  6.0  7.0  6.0  5.0  4.0   4.0
 11.0  10.0  9.0  8.0  8.0  7.0  6.0  7.0  6.0  5.0   4.0

In [12]:
println("Distance is ", Int32(D[r, c]), " edits away")

Distance is 4 edits away


In [13]:
# calculate Leveinshtein ratio
ratio_manual =  (length(source) + length(target) - D[r, c]) / (length(source) + length(target))

0.8095238095238095

### Levenshtein Distance Function

Let's implement all of the above into a function

In [5]:
function levenshtein_distance(source, target)
    """
        levenshtein_distance(source,target)
    
    levenshtein_ratio_and_distance:
    - Calculates levenshtein distance between source and target.
    - Calculates leveshtein ratio between source and target.
    
    Returns Distance, Ratio and Distance Matrix
    """
    
    # get the source and target lengths to create a Distance matrix
    rows = length(source) + 1
    cols = length(target) + 1
    
    # initialize an rows x cols array of zeros (call it d, for distance)
    D = zeros(Float64, (rows, cols))
    
    # let the first row and col be populated by the indices of source and target
    for row = 2:rows
        for col = 2:cols
            D[row, 1] = row-1
            D[1, col] = col-1
        end
    end
    
    # iterate over the matrix to compute cost of deletions, insertions, substitions
    for row = 2:rows
        for col = 2:cols
            if source[row-1] == target[col-1]
                substitutionCost = 0
            else
                substitutionCost = 1 # if we were to compare this to python's levenshtein package, the cost is 2 
            end
            D[row, col] = minimum((D[row-1, col] + 1, # cost of removal
                    D[row, col-1] + 1,  # cost of addition
                    D[row-1, col-1] + substitutionCost)) # cost of substitution
        end
    end 
    
    # calculate Leveinshtein ratio
    ratio = (length(source) + length(target) - D[rows, cols]) / (length(source) + length(target))
    println("Distance is ", Int32(D[rows, cols]), " edits away")
    println("Levenshtein Ratio is ", ratio)
    
    return D[rows, cols], ratio, D
end

levenshtein_distance (generic function with 1 method)

In [ ]:
levenshtein_distance()

In [2]:
source = "Levenshtein"
target = "Lenvinsten"
distance, ratio, distance_matrix = levenshtein_distance(source, target)

Distance is 4 edits away
Levenshtein Ratio is 0.8095238095238095


(4.0, 0.8095238095238095, [0.0 1.0 … 9.0 10.0; 1.0 0.0 … 8.0 9.0; … ; 10.0 9.0 … 4.0 4.0; 11.0 10.0 … 5.0 4.0])

#### Test it out with the examples in the Python-Levenshtein package docs

Ref: https://rawgit.com/ztane/python-Levenshtein/master/docs/Levenshtein.html#Levenshtein-ratio

In [43]:
source = "Hello world!"
target = "Holly grail!"
distance, ratio, distance_matrix = levenshtein_distance(source, target)

Distance is 7 edits away
Levenshtein Ratio is 0.7083333333333334


(7.0, 0.7083333333333334, [0.0 1.0 … 11.0 12.0; 1.0 0.0 … 10.0 11.0; … ; 11.0 10.0 … 7.0 7.0; 12.0 11.0 … 7.0 7.0])

In [44]:
ratio

0.7083333333333334

> Note that the ratio is different from the ratio calculation in Python-Levenshtein package documentation (0.583333....) as that uses `subsitutionCost = 2` (instead of 1) when `s[i] != t[j]`.